### ISSUE TITLE
Service Port

### ISSUE THREAD

**Issue by Ji-Shao** [rpki-client/rpki-client-container#5]
Which port should be exposed when running it on docker?

**Comment by robert-scheck** [comment]
I'm not sure whether I got your question correctly: `rpki-client` does not expose any TCP port, it generates output files which can be accessed using `/var/lib/rpki-client` (usually using [Docker/Podman volumes](https://docs.docker.com/storage/volumes/)). There is e.g. [StayRTR](https://github.com/bgp/stayrtr) in case you would like to solve the gap between `rpki-client` output (e.g. JSON file) and your BGP speaker. And to link these containers, [Docker Compose](https://docs.docker.com/compose/) could be helpful. Does this answer your question?

**Comment by robert-scheck** [comment]
I unfortunately didn't hear back from you, so I assume I've been able to answer your question. If not, feel free to just reply here.
